// Mocks generated by Mockito 5.4.6 from annotations
// in qilema_app/test/unit/features/contacts/contacts_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qilema_app/core/models/contacts_models.dart' as _i2;
import 'package:qilema_app/features/contacts/services/contacts_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContact_0 extends _i1.SmartFake implements _i2.Contact {
  _FakeContact_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContactsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactsApi extends _i1.Mock implements _i3.ContactsApi {
  @override
  _i4.Future<List<_i2.Contact>> getContacts() => (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Contact>>.value(<_i2.Contact>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Contact>>.value(<_i2.Contact>[]),
      ) as _i4.Future<List<_i2.Contact>>);

  @override
  _i4.Future<_i2.Contact> addContact(_i2.Contact? contact) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContact,
          [contact],
        ),
        returnValue: _i4.Future<_i2.Contact>.value(_FakeContact_0(
          this,
          Invocation.method(
            #addContact,
            [contact],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Contact>.value(_FakeContact_0(
          this,
          Invocation.method(
            #addContact,
            [contact],
          ),
        )),
      ) as _i4.Future<_i2.Contact>);

  @override
  _i4.Future<_i2.Contact> updateContact(
    String? contactId,
    _i2.Contact? contact,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContact,
          [
            contactId,
            contact,
          ],
        ),
        returnValue: _i4.Future<_i2.Contact>.value(_FakeContact_0(
          this,
          Invocation.method(
            #updateContact,
            [
              contactId,
              contact,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Contact>.value(_FakeContact_0(
          this,
          Invocation.method(
            #updateContact,
            [
              contactId,
              contact,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Contact>);

  @override
  _i4.Future<bool> deleteContact(String? contactId) => (super.noSuchMethod(
        Invocation.method(
          #deleteContact,
          [contactId],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
