"""
Schema包初始化
"""

from app.schemas.alert import (
    AlertCreate,
    AlertResolveRequest,
    AlertResponse,
    AlertSettingCreate,
    AlertSettingResponse,
    AlertSettingUpdate,
)
from app.schemas.checkin import (
    CheckInCreate,
    CheckInDateQuery,
    CheckInResponse,
    CheckInStats,
    CheckInStatsResponse,
    CheckInStatusResponse,
)
from app.schemas.device import (
    DeviceAlert,
    DeviceBind,
    DeviceCreate,
    DeviceDataCreate,
    DeviceDataQuery,
    DeviceDataResponse,
    DeviceDataUpload,
    DeviceResponse,
    DeviceStatistics,
    DeviceStatusUpdate,
    DeviceThresholdCreate,
    DeviceThresholdResponse,
    DeviceThresholdUpdate,
    DeviceUpdate,
)
from app.schemas.emergency_contact import (
    EmergencyContactCreate,
    EmergencyContactResponse,
    EmergencyContactUpdate,
)
from app.schemas.health_record import (
    AllergyCreate,
    AllergyResponse,
    AllergyUpdate,
    HealthRecordCreate,
    HealthRecordResponse,
    HealthRecordUpdate,
    MedicalHistoryCreate,
    MedicalHistoryResponse,
    MedicalHistoryUpdate,
    MedicationCreate,
    MedicationResponse,
    MedicationUpdate,
)
from app.schemas.sos_request import (
    SOSRequestCreate,
    SOSRequestResponse,
    SOSRequestUpdate,
)
from app.schemas.token import Token, TokenData
from app.schemas.user import UserLogin, UserRegister, UserResponse, UserUpdate

__all__ = [
    "UserRegister",
    "UserLogin",
    "UserResponse",
    "UserUpdate",
    "Token",
    "TokenData",
    "AlertSettingCreate",
    "AlertSettingUpdate",
    "AlertSettingResponse",
    "AlertCreate",
    "AlertResolveRequest",
    "AlertResponse",
    "CheckInCreate",
    "CheckInResponse",
    "CheckInDateQuery",
    "CheckInStats",
    "CheckInStatsResponse",
    "CheckInStatusResponse",
    "DeviceCreate",
    "DeviceUpdate",
    "DeviceResponse",
    "DeviceDataCreate",
    "DeviceDataQuery",
    "DeviceBind",
    "DeviceDataUpload",
    "DeviceDataResponse",
    "DeviceThresholdCreate",
    "DeviceThresholdUpdate",
    "DeviceThresholdResponse",
    "DeviceStatusUpdate",
    "DeviceStatistics",
    "DeviceAlert",
    "HealthRecordCreate",
    "HealthRecordUpdate",
    "HealthRecordResponse",
    "MedicalHistoryCreate",
    "MedicalHistoryResponse",
    "MedicalHistoryUpdate",
    "MedicationCreate",
    "MedicationResponse",
    "MedicationUpdate",
    "AllergyCreate",
    "AllergyResponse",
    "AllergyUpdate",
    "EmergencyContactCreate",
    "EmergencyContactUpdate",
    "EmergencyContactResponse",
    "SOSRequestCreate",
    "SOSRequestUpdate",
    "SOSRequestResponse",
]
